# Generated by Django 5.1.2 on 2024-10-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
