# Generated by Django 5.1.2 on 2024-11-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_dislikes_post_likes_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(
                default=False, help_text='Designates that this user has all'
                'permissions without explicitly assigning them.',
                 verbose_name='superuser status'),
        ),
    ]
