repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: v3.9.2
    hooks:
      - id: flake8
        exclude: '^(env|venv|.venv)/'  # Exclure les dossiers d'environnement virtuel
